INSERT INTO resource (url, name, categoryID) VALUES
("https://www.google.com", "Google", 1),
("https://www.yahoo.com", "Yahoo", 1),
("https://www.ebay.com", "eBay", 1),
("https://www.amazon.com", "Amazon", 1),
("https://www.youtube.com", "YouTube", 2),
("https://www.reddit.com", "Reddit", 3);

INSERT INTO timezone (zone, name) VALUES
("America/New_York", "LANGLEY"),
("America/Los_Angeles", "PACIFIC"),
("America/Chicago", "CENTRAL"),
("Pacific/Honolulu", "HAWAII"),
("Europe/Berlin", "GERMANY"),
("Etc/UTC", "ZULU");

INSERT INTO acronym (acronym, definition) VALUES
("A&P", "analysis and production"),
("A-1", "director of manpower, personnel, and services"),
("A2", "antiaccess"),
("A-2", "intelligence staff officer (USAF)"),
("A-3", "operations directorate (COMAFFOR staff);"),
("operations", "staff officer (USAF)"),
("A-4", "director of logistics (USAF)"),
("A-5", "plans directorate (COMAFFOR staff)"),
("A-6", "communications staff officer (USAF)"),
("A-7", "director of installations and mission support (USAF)"),
("AA", "assessment agent; avenue of approach"),
("AA&E", "arms, ammunition, and explosives"),
("AAA", "antiaircraft artillery; arrival and assembly area"),
("AABB", "American Association of Blood Banks"),
("AAC", "activity address code"),
("AACG", "arrival airfield control group"),
("AADC", "area air defense commander"),
("AADP", "area air defense plan"),
("AAFES", "Army and Air Force Exchange Service"),
("AAFS", "amphibious assault fuel system"),
("AAG", "aeronautical assignment group"),
("AAGS", "Army air-ground system"),
("AAM", "air-to-air missile"),
("AAMDC", "Army air and missile defense command"),
("AAOG", "arrival and assembly operations group"),
("AAP", "Allied administrative publication"),
("AAR", "after action report; after action review; air-to-air refueling area"),
("AATCC", "amphibious air traffic control center"),
("AAV", "amphibious assault vehicle"),
("AB", "air base"),
("ABCA", "American, British, Canadian, Australian, and New Zealand"),
("ABCS", "Army Battle Command System"),
("ABCT", "armored brigade combat team"),
("ABFC", "advanced base functional component"),
("ABFDS", "aerial bulk fuel delivery system"),
("ABGD", "air base ground defense"),
("ABI", "activity-based intelligence"),
("ABL", "airborne laser"),
("ABLTS", "amphibious bulk liquid transfer system");
