SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE account;
TRUNCATE TABLE acronym;
TRUNCATE TABLE information;
TRUNCATE TABLE operation;
TRUNCATE TABLE resource;
TRUNCATE TABLE timezone;
TRUNCATE TABLE weather;
TRUNCATE TABLE login;
TRUNCATE TABLE blame;

SET FOREIGN_KEY_CHECKS=1;