SET FOREIGN_KEY_CHECKS=0;

TRUNCATE TABLE account;
TRUNCATE TABLE acronym;
TRUNCATE TABLE information;
TRUNCATE TABLE operation;
TRUNCATE TABLE resource;
TRUNCATE TABLE timezone;
TRUNCATE TABLE weather;
TRUNCATE TABLE metric;
TRUNCATE TABLE blame;
TRUNCATE TABLE click;

SET FOREIGN_KEY_CHECKS=1;