spring:
  datasource:
    url: ${BLACKPEARL_DB_URL}
    username: ${BLACKPEARL_DB_USERNAME}
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: false
    out-of-order: true
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl:
        auto: create-drop
      use-new-id-generator-mappings: false
  security:
    ignored: /**
#    user:
#      name: jordan
#      password: pearl
CLASSIFIED: UNCLASSIFIED